#!/bin/bash

# omlouvam se za podobu, uplne tomu nerozumim s temi pattern a hold space
# zkousel sem to delat jednoduseji na miste, ale nefungovali mi to a rychle sem se do toho zamotal

# dokud mame co cist
while read line; do 
# dokud radek obsahuje soucet 2 cisel
  while [[ "$line" =~ [0-9][0-9]*\ *\+\ *[0-9][0-9]* ]] ; do 
      fmatch=$( echo "$line" | sed 's/.*[^0-9]\([0-9][0-9]*\ *+\ *[0-9][0-9]*\).*/\1/;
s/^\([0-9][0-9]*\ *+\ *[0-9][0-9]*\)$/\1/;     
 s/^\([0-9][0-9]*\ *+\ *[0-9][0-9]*\).*/\1/;
')
      match=$(echo "$fmatch" | sed 's/^\([0-9][0-9]*\)\ *+\ *\([0-9][0-9]*\)\ *$/, \1 \2/')
      while [[ "$match" =~ ^[0-9]*,\ [0-9][0-9]*\ [0-9][0-9]*$ ]] ; do 
         match=$(echo "$match" | sed 's/\([0-9]*\), \([0-9]*\)\([0-9]\) \([0-9]*\)\([0-9]\)/\1\3\5, \2 \4/')
      done   
      while [[ "$match" =~ ^[0-9]*,\ *[0-9][0-9]*\ *$ ]] ; do
          match=$(echo "$match" | sed 's/\([0-9]*\),\ *\([0-9]*\)\([0-9]\)/\10\3, \2/') 
      done
      match=$( echo $match | sed 's/,//;s/\([0-9][0-9]\)\([0-9]*\)/,0\1:\2/;') 
# scitani ( mame ,0aa:......)
      while ! [[ "$match" =~ ^[0-9]*,[0-9][0-1]:$ ]]; do 
# prevedeni na ..,xxxx:... 
      match=$( echo "$match" | sed '
s/,\(x*\)0/,\1/;
s/,\(x*\)0/,\1/;
s/,\(x*\)1/,x\1/;
s/,\(x*\)1/,x\1/;
s/,\(x*\)2/,xx\1/;
s/,\(x*\)3/,xxx\1/;
s/,\(x*\)4/,xxxx\1/;
s/,\(x*\)5/,xxxxx\1/;
s/,\(x*\)6/,xxxxxx\1/;
s/,\(x*\)7/,xxxxxxx\1/;
s/,\(x*\)8/,xxxxxxxx\1/;
s/,\(x*\)9/,xxxxxxxxx\1/;
')
      match=$( echo "$match" | sed '
s/,\(x*\)0/,\1/;
s/,\(x*\)1/,x\1/;
s/,\(x*\)2/,xx\1/;
s/,\(x*\)3/,xxx\1/;
s/,\(x*\)4/,xxxx\1/;
s/,\(x*\)5/,xxxxx\1/;
s/,\(x*\)6/,xxxxxx\1/;
s/,\(x*\)7/,xxxxxxx\1/;
s/,\(x*\)8/,xxxxxxxx\1/;
s/,\(x*\)9/,xxxxxxxxx\1/;
')
# soucet je presne 10, vice nez 10 - pridame zbytek 1,mene nez 10  dame 0 nebo 0
      match=$( echo "$match" | sed 's/,x\{10\}:/,01:/;s/,\(xx*\)x\{10\}:/,\11:/;s/,:/,00:/;s/,\(x\{1,9\}\):/,\10:/' )   
# scitame zbylych 1-9 x
      match=$( echo "$match" | sed '
s/xxxxxxxxx/9/;
s/xxxxxxxx/8/;
s/xxxxxxx/7/;
s/xxxxxx/6/;
s/xxxxx/5/;
s/xxxx/4/;
s/xxx/3/;
s/xx/2/;
s/x/1/;
') 
# prevedeni souctu do vysledku a pripraveni na soucet dalsich 2 cisel a zbytku
      match=$( echo "$match" |sed 's/\([0-9]*\),\([0-9]\)\([0-1]\):\([0-9][0-9]\)/\2\1,\3\4:/' )
      done
# nyni ve tvaru nnn,a[0-1]:
  match=$( echo "$match" | sed 's/\([0-9]*\),\([0-9]\)0:/\2\1/;s/\([0-9]*\),\([0-9]\)1:/1\2\1/')
  line=$( echo "$line" | sed "s/$fmatch/$match/" )
  done
  echo $line
done

